version: '3.6'

services:

  bytem-app:
<<<<<<< HEAD
    image: liberbyteadmin/bytem:app-done
    container_name: bytem-app
    hostname: bytem-app
    restart: "always"
=======
    image: liberbyteadmin/bytem:app-fixed
    container_name: bytem-app
    hostname: bytem-app
    restart: "always"
      #build:
      #context: .
      # dockerfile: ./Dockerfile.bytemApp
>>>>>>> f0953e4ff9ca93bebed4b52d29b4edcebd4d797d
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./generated_config_files/nginx_config:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - bytem-network

  bytem-be:
<<<<<<< HEAD
    image: liberbyteadmin/bytem:be-done
=======
    image: liberbyteadmin/bytem:be-fixed
>>>>>>> f0953e4ff9ca93bebed4b52d29b4edcebd4d797d
    container_name: bytem-be
    hostname: bytem-be
    restart: always
    depends_on:
      - bytem-synapse
    env_file:
      - .env.bytem
<<<<<<< HEAD
=======
        #build:
        #context: .
        #dockerfile: ./Dockerfile.backend
>>>>>>> f0953e4ff9ca93bebed4b52d29b4edcebd4d797d
    ports:
      - 9999:9999
      - 3000:3000
    volumes:
<<<<<<< HEAD
=======
      # - ./solr/data:/app/solr/data
>>>>>>> f0953e4ff9ca93bebed4b52d29b4edcebd4d797d
      - ./.env.bytem:/app/.env.bytem
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - bytem-network

  bytem-bot:
<<<<<<< HEAD
    image: liberbyteadmin/bytem:bot-done
=======
    image: liberbyteadmin/bytem:bot-latest
>>>>>>> f0953e4ff9ca93bebed4b52d29b4edcebd4d797d
    container_name: bytem-bot
    hostname: bytem-bot
    restart: always
    depends_on:
      - bytem-synapse
<<<<<<< HEAD
=======
        #build:
        #context: .
        #dockerfile: ./Dockerfile.bot
>>>>>>> f0953e4ff9ca93bebed4b52d29b4edcebd4d797d
    ports:
      - 4000:4000
    volumes:
      - ./solr/data:/solr/data
      - ./.env.bytem:/.env.bytem
    networks:
      - bytem-network

  bytem-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: bytem-rabbitmq
    hostname: bytem-rabbitmq
    restart: always
    env_file:
      - .env.bytem
<<<<<<< HEAD
=======
    # environment: 
    #   - RABBITMQ_DEFAULT_USER=bytem
    #   - RABBITMQ_DEFAULT_PASS=bytem
    #   - RABBITMQ_DEFAULT_VHOST=bytem
>>>>>>> f0953e4ff9ca93bebed4b52d29b4edcebd4d797d
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - bytem-rabbitmq-data:/var/lib/rabbitmq/
      - bytem-rabbitmq-log:/var/log/rabbitmq
    networks:
      - bytem-network

  bytem-solr:
    image: solr:9.5.0
    container_name: bytem-solr
    hostname: bytem-solr
    restart: always
    user: root
    depends_on:
      - bytem-be
    ports:
     - "8983:8983"
    volumes:
      - ./solr:/var/solr
    command:
      - -force
<<<<<<< HEAD
=======
      # - solr-precreate
      # - gettingstarted
>>>>>>> f0953e4ff9ca93bebed4b52d29b4edcebd4d797d
    networks:
      - bytem-network

  bytem-synapse:
<<<<<<< HEAD
    image: docker.io/matrixdotorg/synapse:v1.123.0
=======
    image: liberbyteadmin/bytem:synapse
>>>>>>> f0953e4ff9ca93bebed4b52d29b4edcebd4d797d
    container_name: bytem-synapse
    hostname: bytem-synapse
    restart: always
    depends_on:
      - bytem-synapse-db
    environment:
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
    ports:
      - 8008:8008
      - 8009:8009
      - 8448:8448
    volumes:
      - ./generated_config_files/synapse_config:/data
    networks:
      - bytem-network
<<<<<<< HEAD
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y wget &&
        wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 &&
        chmod +x /usr/local/bin/yq &&
        exec /start.py
      "
=======
>>>>>>> f0953e4ff9ca93bebed4b52d29b4edcebd4d797d
  
  bytem-synapse-db:
    image: docker.io/postgres:14-alpine
    container_name: bytem-synapse-db
    hostname: bytem-synapse-db
    restart: always
    env_file:
      - .env.bytem
    environment:
<<<<<<< HEAD
=======
      # - POSTGRES_USER=synapse
      # - POSTGRES_PASSWORD=bytemsynapse
>>>>>>> f0953e4ff9ca93bebed4b52d29b4edcebd4d797d
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - 5432:5432
    volumes:
      - bytem-synapse-db-data:/var/lib/postgresql/data
    networks:
      - bytem-network

  bytem-promtail:
    image: grafana/promtail:2.9.0
    container_name: bytem-promtail
    hostname: bytem-promtail
    restart: always
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - bytem-network

  bytem-pwa:
    image: liberbyteadmin/bytem:pwa
    container_name: bytem-pwa
    hostname: bytem-pwa
    restart: always
    ports:
      - 8002:80
    networks:
      - bytem-network

networks:
  bytem-network:
    name: bytem-network
    driver: bridge

volumes:
  bytem-rabbitmq-data:
    name: bytem-rabbitmq-data
  bytem-rabbitmq-log:
    name: bytem-rabbitmq-log
<<<<<<< HEAD
=======
  # bytem-solr-data:
  #   name: bytem-solr-data
>>>>>>> f0953e4ff9ca93bebed4b52d29b4edcebd4d797d
  bytem-synapse-db-data:
    name: bytem-synapse-db-data
