server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://94.237.103.252:3100/loki/api/v1/push

scrape_configs:
  - job_name: bytem-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/bytem-(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_name']
        regex: '/bytem-(.*)'
        target_label: 'job'
        replacement: 'bytem-bm3'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'

  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system-bm3
          __path__: /var/log/syslog
