#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

[ -f .env ] || { echo "ERROR: .env is missing. Run ./env_setup.sh first." >&2; exit 1; }

echo "Regenerating Synapse configuration from the configured market list..."
docker compose --env-file .env up -d --force-recreate bytem-synapse

echo "Waiting for Synapse..."
deadline=$((SECONDS + 120))
until docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{end}}' bytem-synapse 2>/dev/null | grep -qx healthy; do
  if [ "$SECONDS" -ge "$deadline" ]; then
    docker compose logs --tail 100 bytem-synapse
    echo "ERROR: Synapse did not become healthy." >&2
    exit 1
  fi
  sleep 3
done

echo "Active federation whitelist:"
docker exec bytem-synapse awk '
  /^federation_domain_whitelist:/ {printing=1}
  printing && /^[^[:space:]#]/ && !/^federation_domain_whitelist:/ {exit}
  printing {print}
' /data/homeserver.yaml

echo "Whitelist refreshed. It is now generated by the Synapse image; no host config is edited."
